### ISSUE TITLE
JS を ES6 の書き方にしたい

### ISSUE THREAD

**Issue by YutaNakamizo** [kazuki19992/Vane11ope-strongest-handle#5]
const とアロー関数.

**Comment by kazuki19992** [comment]
確認してマージしました！！ありがとうございます！！！
`tweet-share.js`ってあんなに短くまとまっちゃうんですね……！！！すごい……
マージしたのでこのissueと#4のissueもクローズしちゃいますね！！ありがとうございます！感謝です！
